config/routes.rb
Rails.application.routes.draw do
  resources :tasks, only: [:index, :create, :new, :destroy] do
    member do
      patch 'complete'
      patch 'uncomplete'
    end 
    collection do 
      patch :sort
    end
  end
  root :to => 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:destroy, :complete, :uncomplete]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.order(:position)
    @task = Task.new
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.js  { flash[:notice] = "Task was successfully added" }
        format.json { render :show, status: :created, location: @task }
      else
        format.js
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def complete
    respond_to do |format|
      if @task.update_attributes(:completed => params[:completed])
        format.js  { flash[:notice] = "Task was completed!" }
      end
    end
  end

  def uncomplete
    respond_to do |format|
      if @task.update_attributes(:completed => params[:completed])
        format.js  { flash[:notice] = "Task was incompleted!" }
      end
    end
  end

  def sort
    params[:taskitem].each_with_index do |id, index|
      Task.where(id: id).update_all(position: index + 1)
    end

    head :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def task_position_value
      Task.pluck(:position).to_a.max == nil ?  1 : Task.pluck(:position).to_a.max + 1
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params[:task][:position] = task_position_value
      params.require(:task).permit(:name, :completed, :position)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
     <p class="notice"><%= notice %></p>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-dange role="alert">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>

<script type="text/javascript">
  setTimeout("$('.alert').fadeOut(3000).slideUp(500)");
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagementSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task, remote: true) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-inline cr-form-inline">
    <%= f.text_field :name, required: true, class: 'form-control cr-form-control task_name', placeholder: "Task name"  %>
    <%= f.submit "Add task", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<ul id="taskitem_<%= task.id %>" class="list-group-item "> 
  <% if task.completed %>
    <li id="str_<%= task.id %>" class="strike"><%= task.name %>
      <%= check_box_tag 'completed', task.id , task.completed, 
                         :class => "task-check_#{task.id} all pull-right", data: {
                         remote: true} %>
    </li>
    <% else %>
      <li id="str_<%= task.id %>"><%= task.name %>
      <%= check_box_tag 'completed', task.id , task.completed, 
                         :class => "task-check_#{task.id} all pull-right", data: {
                         remote: true} %>
    </li>
  <% end %>
</ul>

<%# JS code for complete/incomplete tasks %>
<script type="text/javascript">
  $(".task-check_<%= task.id %>").on('click', function(){
    if (this.checked){
      $.ajax({
        url: '/tasks/'+this.value+'/complete',
        type: 'PATCH',
        data: {"completed": this.checked}, 
        success: function () {
          $('#str_<%= task.id%>').addClass("strike");
          alert("Task was completed!");
        }
      });
    }
    else {
      $.ajax({
        url: '/tasks/'+this.value+'/uncomplete',
        type: 'PATCH',
        data: {"completed": this.checked}, 
        success: function () {
          $('#str_<%= task.id%>').removeClass("strike");
          alert("Task was incompleted!");
        }
      });
    }
  });
</script>

app/views/tasks/create.js.erb
$('.task_name').val('');

$('#item').append('<%= j render @task %>'); 

<% if @task.errors.empty? %>
  $(".notice").html('<%= j render partial: "layouts/alerts", locals: { notice: flash[:notice] } %>');
<% else %>
  $(".notice").html('<%= j render partial: "layouts/alerts", locals: { alert: flash[:alert] } %>');
<% end %>

app/views/tasks/index.html.erb
<div class="notice"></div>
<div class="row text-center">
  <div class="col-md-6 col-md-offset-3">
    <div class="task-area"> 
      <h1>Task Management System</h1>
        <div id="item" class="items" data-url="<%= sort_tasks_path%>"><%= render @tasks %></div>
        <%= render partial: "form" %>
    </div>
  </div>
</div>
<div class="modal"></div>

<script type="text/javascript">
  $body = $("body");
  $(document).on({
      ajaxStart: function() { $body.addClass("loading");   },
      ajaxStop: function() { $body.removeClass("loading"); }    
  });
</script>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>